version: '3'

services:
  mcp-nav:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcp-nav
    container_name: mcp-nav-server
    ports:
      - "9090:9090"
    environment:
      - MCP_NAV_PORT=9090
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:9090/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 